services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - BOT_TOKEN=123:BOT_TOKEN
      - BOT_USERNAME=BotUsername_bot
    networks:
      - net
    depends_on:
      - db
  db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - net
    ports:
      - 5432:5432
networks:
  net:
